# use these packing instructions
# https://enterprise-docs.anaconda.com/en/latest/data-science-workflows/data/instantclient.html

{% set version="21.4.0.0.0" %}
package:
  name: oracle-instantclient-sqlplus
  version: {{ version }}

source:
  url: https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-{{ version }}dbru.zip
  sha256: 9b118bf8065dcd4f332fd1e7ae00186c9b2dd1cfd57e9cefcac6a6a367c8d388
  folder: instantclient-sqlplus

build:
  number: 1
