# use these packing instructions
# https://enterprise-docs.anaconda.com/en/latest/data-science-workflows/data/instantclient.html

{% set version="21.4.0.0.0" %}
package:
  name: oracle-instantclient-sqlplus
  version: {{ version }}

source:
  url: https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-{{ version }}dbru.zip
  sha256: 58714313680f67334ca36a684a4f4a7344842ffe224192f5781b9f07f0750009
  folder: instantclient-sqlplus

build:
  number: 1
